eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6002/eureka/

system:
  uploadPath: /doc/image
  uploadAudioPath: /doc/audio
  uploadAppPath: /doc/app
  uploadDevlog: /doc/devlog
  uploadSize: 20480KB